---
- name: Linux hosts | RHEL Subscription attach
  hosts: "{{ target_hosts | default('linux_hosts', true) }}"
  become: true
  tasks:
    - name: Register system with Red Hat Subscription Manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
