- name: Windows hosts | Remove package from Windows Server
  hosts: windows_hosts
  tasks:
    - name: Windows hosts | Remove PuTTY
      ansible.windows.win_package:
        path: C:\ansible_examples\putty-64bit-0.78-installer.msi
        state: absent

    - name: Windows hosts | Remove Installer
      ansible.windows.win_file:
        name: C:\ansible_examples\putty-64bit-0.78-installer.msi
        state: absent
